export const STORY_PACK_IDS = [
  'mahabharata',
  'ramayana',
  'shiv_puran',
  'bhagavad_gita',
  'hanuman',
  'krishna_leela',
  'devi_mahatmya',
  'vedic_wisdom',
  'upanishads',
  'puranas',
  'ancient_history',
  'saints_sages',
];

export const FEATURED_STORY_PACK_IDS = STORY_PACK_IDS.slice(0, 5);

export const STORY_PACK_LABELS = {
  mahabharata: {
    en: 'Mahabharata',
    hi: 'महाभारत',
    te: 'మహాభారతం',
    ta: 'மகாபாரதம்',
    kn: 'ಮಹಾಭಾರತ',
    ml: 'മഹാഭാരതം',
  },
  ramayana: {
    en: 'Ramayanam',
    hi: 'रामायण',
    te: 'రామాయణం',
    ta: 'இராமாயணம்',
    kn: 'ರಾಮಾಯಣ',
    ml: 'രാമായണം',
  },
  shiv_puran: {
    en: 'Shiv Puranam',
    hi: 'शिव पुराण',
    te: 'శివ పురాణం',
    ta: 'சிவ புராணம்',
    kn: 'ಶಿವ ಪುರಾಣ',
    ml: 'ശിവ പുരാണം',
  },
  bhagavad_gita: {
    en: 'Bhagavad Gita',
    hi: 'भगवद गीता',
    te: 'భగవద్గీత',
    ta: 'பகவத் கீதை',
    kn: 'ಭಗವದ್ಗೀತೆ',
    ml: 'ഭഗവദ് ഗീത',
  },
  hanuman: {
    en: 'Hanuman',
    hi: 'हनुमान',
    te: 'హనుమాన్',
    ta: 'அனுமன்',
    kn: 'ಹನುಮಾನ್',
    ml: 'ഹനുമാൻ',
  },
  krishna_leela: {
    en: 'Krishna Leela',
    hi: 'कृष्ण लीला',
    te: 'కృష్ణలీల',
    ta: 'கிருஷ்ண லீலை',
    kn: 'ಕೃಷ್ಣ ಲೀಲೆ',
    ml: 'കൃഷ്ണലീല',
  },
  devi_mahatmya: {
    en: 'Devi Mahatmya',
    hi: 'देवी महात्म्य',
    te: 'దేవీ మహాత్మ్యం',
    ta: 'தேவி மாஹாத்மியம்',
    kn: 'ದೇವಿ ಮಹಾತ್ಮ್ಯ',
    ml: 'ദേവീ മഹാത്മ്യം',
  },
  vedic_wisdom: {
    en: 'Vedic Wisdom',
    hi: 'वैदिक ज्ञान',
    te: 'వేదజ్ఞానం',
    ta: 'வேத ஞானம்',
    kn: 'ವೇದ ಜ್ಞಾನ',
    ml: 'വേദ വിജ്ഞാനം',
  },
  upanishads: {
    en: 'Upanishads',
    hi: 'उपनिषद',
    te: 'ఉపనిషత్తులు',
    ta: 'உபநிஷதங்கள்',
    kn: 'ಉಪನಿಷತ್ತುಗಳು',
    ml: 'ഉപനിഷത്തുകൾ',
  },
  puranas: {
    en: 'Puranas',
    hi: 'पुराण',
    te: 'పురాణాలు',
    ta: 'புராணங்கள்',
    kn: 'ಪುರಾಣಗಳು',
    ml: 'പുരാണങ്ങൾ',
  },
  ancient_history: {
    en: 'Ancient History',
    hi: 'प्राचीन इतिहास',
    te: 'ప్రాచీన చరిత్ర',
    ta: 'பண்டைய வரலாறு',
    kn: 'ಪ್ರಾಚೀನ ಇತಿಹಾಸ',
    ml: 'പ്രാചീന ചരിത്രം',
  },
  saints_sages: {
    en: 'Saints & Sages',
    hi: 'संत और ऋषि',
    te: 'సంతులు & ఋషులు',
    ta: 'சான்றோர் & முனிவர்கள்',
    kn: 'ಸಂತರು & ಋಷಿಗಳು',
    ml: 'സന്തന്മാർ & മുനിമാർ',
  },
};

